# Generated by Django 3.0.7 on 2020-07-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='rugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('postcode', models.IntegerField()),
                ('number', models.IntegerField()),
                ('problem', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=400)),
            ],
        ),
    ]
